name: Build Ubuntu kernel
on:
  workflow_dispatch:




env:
  _distro: "Ubuntu"
  _git_mirror: "kernel.org"
  _logging_use_script: "no"
  _install_after_building: "no"
  _debugdisable: "true"
  _noccache: "true"
  _STRIP: "true"
  _kernel_work_folder: "/tmp"
  _kernel_source_folder: "/tmp"



jobs:
  build-kernel:

    runs-on: ubuntu-latest

    steps:
      - name: Free up space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt-get clean
      # - name: "[debug] make dummy modprobed-db file for faster ci"
      #   run: |
      #     touch "${_modprobeddb_db_path}"
      #     echo "${_modprobeddb_db_path}"
      - uses: actions/checkout@v4
      - name: Install deps and compile kernel
        run: yes '' | ./install.sh install
        # run: |
        #   mkdir -p "$PKGDEST"
        #   echo "test" > "$PKGDEST"/linux-$_cpusched.pkg.tar.zst

      - name: Cleanup useless DEB files
        run: rm -rf DEBS/*dbg*.deb DEBS/*libc-dev*.deb

      - name: rename kernel config
        run: mv kernelconfig.new kernelconfig.ubuntu.${{ env._cpusched }}.txt

      - uses: actions/upload-artifact@v4
        with:
          name: ubuntu-kernel-packages-${{ env._cpusched }}
          path: |
            ${{ github.workspace }}/DEBS/*.deb
            ${{ github.workspace }}/kernelconfig*.txt
            ${{ github.workspace }}/prepare.log.txt
